openapi: 3.0.0
info:
  version: '2'
  title: 'RideShareAPI'
  description: ''
paths: {}
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/khairston/RideShare/2